# Generated by Django 4.0.2 on 2022-03-01 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dehazing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='img',
            new_name='image',
        ),
    ]
